apiVersion: operator.ibm.com/v1
kind: CatalogUI
metadata:
  name: catalog-ui
spec:
  catalogui:
    image:
      imageRegistry: quay.io/opencloudio
      pullPolicy: IfNotPresent
      repository: icp-catalog-ui
      tag: 3.2.4
    resources:
      limits:
        cpu: 300m
        memory: 300Mi
      requests:
        cpu: 300m
        memory: 300Mi
  replicaCount: 1